[package]
name = "dovi_tool"
version = "0.1.0"
authors = ["quietvoid"]
edition = "2018"
license = "MIT"

[dependencies]
structopt = "0.3.20"
indicatif = "0.15.0"
regex = "1.4.2"
ansi_term = "0.12.1"
bitvec = "0.19.4"
crc32fast = "1.2.1"
